services:
  postgres-db:
    container_name: postgress-db
    image: postgres:17.2-alpine3.21
    restart: always
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5433:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'

  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - '1521:1521'
    environment:
      - ORACLE_PWD=SenhaForteAqui123!
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped

  sqlserver-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-db
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SenhaForteAqui123!
      - MSSQL_PID=Developer
      - MSSQL_DATABASE=local
    ports:
      - '1433:1433'
    volumes:
      - mssql-data:/var/opt/mssql/data
    networks:
      - db_network

  # app:
  #   container_name: app
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #     target: development
  #   volumes:
  #     - .:/usr/src/app
  #   env_file:
  #   - .env
  #   command: npm run start:dev
  #   ports:
  #     - 4000:4000
  #   depends_on:
  #     - db

volumes:
  db-data:
    driver: local
  oracle-data:
    driver: local
  mssql-data:
    driver: local

networks:
  db_network:
    driver: bridge
