import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateUserTable1734429739029 implements MigrationInterface {
    name = 'CreateUserTable1734429739029'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" number GENERATED BY DEFAULT AS IDENTITY, "username" varchar2(100) NOT NULL, "email" varchar2(255) NOT NULL, "name" varchar2(255) NOT NULL, "passhash" varchar2(255) NOT NULL, "role" varchar2(20) DEFAULT 'user' NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "deleted_at" timestamp NOT NULL, "status" number DEFAULT 1 NOT NULL, "last_login" timestamp NOT NULL, "last_login_ip" varchar2(255) NOT NULL, "visibility" number DEFAULT 1 NOT NULL, "admin" number DEFAULT 0 NOT NULL, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
